#!/bin/bash

# Vercel Environment Variables Setup Script
# This helps you copy the exact values from .env.local to Vercel

echo "================================================"
echo "🚀 VERCEL DEPLOYMENT - ENVIRONMENT VARIABLES"
echo "================================================"
echo ""
echo "Your app is already deployed to Vercel!"
echo "Now you need to add environment variables."
echo ""
echo "================================================"
echo "📋 COPY THESE VALUES TO VERCEL DASHBOARD"
echo "================================================"
echo ""
echo "Go to: https://vercel.com/dashboard"
echo "Click: zentry-zen-flow project"
echo "Navigate: Settings → Environment Variables"
echo ""
echo "Add these 4 variables (select ALL environments):"
echo ""
echo "-------------------------------------------"
echo "Variable 1:"
echo "-------------------------------------------"
echo "Name: VITE_GEMINI_API_KEY"
echo "Value: AIzaSyDBNueAhIjMgvcASQY4PHvoBlgZS6Omwfc"
echo ""
echo "-------------------------------------------"
echo "Variable 2:"
echo "-------------------------------------------"
echo "Name: VITE_AI_PROVIDER"
echo "Value: gemini"
echo ""
echo "-------------------------------------------"
echo "Variable 3:"
echo "-------------------------------------------"
echo "Name: VITE_SUPABASE_URL"
echo "Value: https://vnixcafcspbqhuytciog.supabase.co"
echo ""
echo "-------------------------------------------"
echo "Variable 4:"
echo "-------------------------------------------"
echo "Name: VITE_SUPABASE_ANON_KEY"
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuaXhjYWZjc3BicWh1eXRjaW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0NzI2NDQsImV4cCI6MjA3NTA0ODY0NH0.lZEkFrOU3chVCLdTZrQZGgp8riSe-UNlTdfRQJNEg-0"
echo ""
echo "================================================"
echo "⚠️  IMPORTANT STEPS:"
echo "================================================"
echo ""
echo "For EACH variable:"
echo "  1. Click 'Add New' in Vercel"
echo "  2. Enter the Name (exactly as shown above)"
echo "  3. Enter the Value (copy-paste from above)"
echo "  4. ✅ Check: Production"
echo "  5. ✅ Check: Preview"
echo "  6. ✅ Check: Development"
echo "  7. Click 'Save'"
echo ""
echo "================================================"
echo "🔄 AFTER ADDING ALL VARIABLES:"
echo "================================================"
echo ""
echo "  1. Go to 'Deployments' tab"
echo "  2. Click '...' on latest deployment"
echo "  3. Click 'Redeploy'"
echo "  4. Wait 2-3 minutes"
echo "  5. Test your app!"
echo ""
echo "================================================"
echo "✅ Your live app URL (approximately):"
echo "================================================"
echo ""
echo "https://zentry-zen-flow.vercel.app"
echo "(or similar - check Vercel dashboard for exact URL)"
echo ""
echo "================================================"
echo "🎯 VERIFY IT'S WORKING:"
echo "================================================"
echo ""
echo "1. Open your deployed app"
echo "2. Go to AI Chat page"
echo "3. Send a message: 'Hello'"
echo "4. Should get Gemini response!"
echo "5. Check browser console (F12) - no 403 errors"
echo ""
echo "================================================"
echo ""
echo "📱 Open Vercel Dashboard now:"
echo "https://vercel.com/dashboard"
echo ""
echo "================================================"
